[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
minversion = 6.0

# Filters for Playwrites warnings 
filterwarnings =
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore::DeprecationWarning