[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
minversion = 6.0

# addopts = --alluredir=reports/allure-results

# Filters for Playwright warnings 
filterwarnings =
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore::DeprecationWarning